CREATE TABLE CUSTOMERS (ID INTEGER NOT NULL, PRIMARY KEY (ID))
CREATE TABLE COLLEAGUES (ID INTEGER NOT NULL, DEPARTMENT VARCHAR(255), EMAIL VARCHAR(255), FIRSTNAME VARCHAR(255), LASTNAME VARCHAR(255), TITLE VARCHAR(255), PRIMARY KEY (ID))
