INSERT INTO Categories VALUES(default,'Beverages','Soft drinks, coffees, teas, beers, and ales','img/01.jpg');
INSERT INTO Categories VALUES(default,'Condiments','Sweet and savory sauces','img/01.jpg');
INSERT INTO Categories VALUES(default,'Dairy Products','Cheeses','img/01.jpg');
INSERT INTO Categories VALUES(default,'Meat/Poultry','Prepared meats','img/01.jpg');
INSERT INTO Categories VALUES(default,'Seafood','Seaweed and fish','img/01.jpg');

INSERT INTO Products VALUES(default, 'Chai', 1, '10 boxes x 20 bags', 13, 39);
INSERT INTO Products VALUES(default, 'Chang', 1, '24 - 12 oz bottles', 19, 12);
INSERT INTO Products VALUES(default, 'Aniseed Syrup', 2, '12 - 550 ml bottles', 10, 13);
INSERT INTO Products VALUES(default, 'Chef Anton''s Cajun Seasoning', 2, '43 - 4 oz jars', 22, 53);
INSERT INTO Products VALUES(default, 'Chef Anton''s Gumbo Mix', 2, '34 boxes', 21.35, 0);
INSERT INTO Products VALUES(default, 'Grandma''s Boysenberry Spread',  2, '12 - 3 oz jars', 25, 120);
INSERT INTO Products VALUES(default, 'Uncle Bob''s Organic Dried Pears', 2, '12 - 1 lb pkgs.', 30, 15);
INSERT INTO Products VALUES(default, 'Northwoods Cranberry Sauce',  2, '12 - 12 oz jars', 40, 4);
INSERT INTO Products VALUES(default, 'Mishi Kobe Niku', 4, '13 - 500 g pkgs.', 92, 29);
INSERT INTO Products VALUES(default, 'Ikura',  3, '12 - 200 ml jars', 31, 31);
INSERT INTO Products VALUES(default, 'Queso Cabrales',  4, '1 kg pkg.', 21, 22);
INSERT INTO Products VALUES(default, 'Queso Manchego La Pastora',  4, '10 - 500 g pkgs.', 33, 34);
INSERT INTO Products VALUES(default, 'Konbu',  3, '2 kg box', 4, 24);
INSERT INTO Products VALUES(default, 'Tofu',  2, '40 - 100 g pkgs.', 23.25, 35);
INSERT INTO Products VALUES(default, 'Genen Shouyu',  2, '24 - 250 ml bottles', 15.5, 39);
INSERT INTO Products VALUES(default, 'Pavlova',  3, '32 - 500 g boxes', 12.45, 29);
INSERT INTO Products VALUES(default, 'Alice Mutton',  4, '20 - 1 kg tins', 39, 1);
INSERT INTO Products VALUES(default, 'Carnarvon Tigers',  3, '14 kg pkg.', 42.5, 42);
INSERT INTO Products VALUES(default, 'Teatime Chocolate Biscuits',  3, '10 boxes x 12 pieces', 9.2, 25);
INSERT INTO Products VALUES(default, 'Sir Rodney''s Marmalade',  3, '30 gift boxes', 31, 40);
INSERT INTO Products VALUES(default, 'Sir Rodney''s Scones', 3, '24 pkgs. x 4 pieces', 10, 3);
INSERT INTO Products VALUES(default, 'Gustaf''s Knckebrd',  5, '24 - 500 g pkgs.', 21, 104);
INSERT INTO Products VALUES(default, 'Tunnbrd',  5, '12 - 250 g pkgs.', 9, 41);
INSERT INTO Products VALUES(default, 'Guaran Fantstica',  1, '12 - 355 ml cans', 4.5, 20);
INSERT INTO Products VALUES(default, 'NuNuCa Nu-Nougat-Creme',  3, '20 - 450 g glasses', 14, 24);
INSERT INTO Products VALUES(default, 'Gumbr Gummibrchen',  3, '100 - 250 g bags', 31.23, 15);
INSERT INTO Products VALUES(default, 'Schoggi Schokolade',  3, '100 - 100 g pieces', 43.9, 49);
INSERT INTO Products VALUES(default, 'Rssle Sauerkraut',  2, '25 - 325 g cans', 45.4, 24);
INSERT INTO Products VALUES(default, 'Thringer Rostbratwurst',  4, '50 bags x 30 sausgs.', 123.29, 1);
INSERT INTO Products VALUES(default, 'Nord-Ost Matjeshering', 3, '10 - 200 g glasses', 25.39, 10);
INSERT INTO Products VALUES(default, 'Gorgonzola Telino',  4, '12 - 100 g pkgs', 12.5, 0);
INSERT INTO Products VALUES(default, 'Mascarpone Fabioli',  4, '24 - 200 g pkgs.', 32, 9);
INSERT INTO Products VALUES(default, 'Geitost',  4, '500 g', 2.5, 112);
INSERT INTO Products VALUES(default, 'Sasquatch Ale', 1, '24 - 12 oz bottles', 14, 111);
INSERT INTO Products VALUES(default, 'Steeleye Stout',  1, '24 - 12 oz bottles', 13, 20);
INSERT INTO Products VALUES(default, 'Inlagd Sill', 3, '24 - 250 g  jars', 19, 112);
INSERT INTO Products VALUES(default, 'Gravad lax',  3, '12 - 500 g pkgs.', 24, 11);
INSERT INTO Products VALUES(default, 'Cte de Blaye',  1, '12 - 25 cl bottles', 243.5, 12);
INSERT INTO Products VALUES(default, 'Chartreuse verte',  1, '250 cc per bottle', 13, 49);
INSERT INTO Products VALUES(default, 'Boston Crab Meat',  3, '24 - 4 oz tins', 13.4, 123);
INSERT INTO Products VALUES(default, 'Jack''s New England Clam Chowder',  3, '12 - 12 oz cans', 9.45, 35);
INSERT INTO Products VALUES(default, 'Singaporean Hokkien Fried Mee',  5, '32 - 1 kg pkgs.', 14, 24);
INSERT INTO Products VALUES(default, 'Ipoh Coffee',  1, '14 - 500 g tins', 44, 12);
INSERT INTO Products VALUES(default, 'Gula Malacca',  2, '20 - 2 kg bags', 19.45, 22);
INSERT INTO Products VALUES(default, 'Rogede sild',  3, '1k pkg.', 9.5, 5);
INSERT INTO Products VALUES(default, 'Spegesild',  3, '4 - 450 g glasses', 12, 95);
INSERT INTO Products VALUES(default, 'Zaanse koeken',  3, '10 - 4 oz boxes', 9.5, 34);
INSERT INTO Products VALUES(default, 'Chocolade',  3, '10 pkgs.', 12.25, 15);
INSERT INTO Products VALUES(default, 'Maxilaku',  3, '24 - 50 g pkgs.', 20, 10);
INSERT INTO Products VALUES(default, 'Valkoinen suklaa',  3, '12 - 100 g bars', 14.25, 45);
INSERT INTO Products VALUES(default, 'Manjimup Dried Apples', 2, '50 - 300 g pkgs.', 53, 20);
INSERT INTO Products VALUES(default, 'Filo Mix',  5, '14 - 2 kg boxes', 2, 33);
INSERT INTO Products VALUES(default, 'Perth Pasties', 4, '43 pieces', 32.3, 1);
INSERT INTO Products VALUES(default, 'Tourtire',  4, '14 pies', 2.45, 21);
INSERT INTO Products VALUES(default, 'Pt chinois',  4, '24 boxes x 2 pies', 24, 115);
INSERT INTO Products VALUES(default, 'Gnocchi di nonna Alice', 5, '24 - 250 g pkgs.', 33, 21);